name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:7.5.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "nc -z localhost 9092"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for Kafka to be ready
        run: |
          echo "Waiting for Kafka to be ready..."
          sleep 30  # Adjust if needed for readiness

#      - name: Download embedded SQL schema
#        run: |
#          curl -L -o src/main/resources/schema.sql https://raw.githubusercontent.com/<your-org>/<repo>/main/sql/schema.sql
#
#      - name: (Optional) Download data.sql for test data
#        run: |
#          curl -L -o src/main/resources/data.sql https://raw.githubusercontent.com/<your-org>/<repo>/main/sql/data.sql

      - name: Build Maven project
        run: mvn clean package

      - name: Start Spring Boot app in background
        run: |
          chmod +x *
          ./run_cucumber.sh ${{ github.workspace }}

      - name: Upload API Report
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: ${{ github.workspace }}/APIReport.html


