name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: wurstmeister/zookeeper:3.4
        ports:
          - 2181:2181

      kafka:
        image: wurstmeister/kafka:2.13-2.8.0
        env:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
          - 9092:9092
        options: >-
          --health-cmd "nc -z localhost 9092"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for Kafka to be ready
        run: |
          echo "Waiting for Kafka to be ready..."
          sleep 30  # Adjust if needed for readiness

      - name: Build Maven project
        run: mvn clean install -DskipTests

      - name: Build Docker image locally
        run:
          java -jar ${{ github.workspace }}/Employee-Management-System-0.0.1-SNAPSHOT.jar
          java -jar ${{ github.workspace }}/target/ApiFramwork-0.0.1-SNAPSHOT.jar
          mvn clean install

      - name: Upload API Report
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: ${{ github.workspace }}/APIReport.html


